#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const checkOnly = process.argv.includes("--check");

const registryPath = path.join(repoRoot, "release-registry.json");
if (!fs.existsSync(registryPath)) {
  console.error(`Missing registry: ${registryPath}`);
  process.exit(1);
}

const registry = JSON.parse(fs.readFileSync(registryPath, "utf8"));
const { paths = {}, commands = [], codex } = registry;

if (!codex) {
  console.error("Missing codex section in release-registry.json.");
  process.exit(1);
}

function abs(relPath) {
  return path.resolve(repoRoot, relPath);
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function mustExist(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing file: ${path.relative(repoRoot, filePath)}`);
  }
}

function mustRead(filePath) {
  mustExist(filePath);
  return fs.readFileSync(filePath, "utf8");
}

function readJson(filePath) {
  return JSON.parse(mustRead(filePath));
}

function writeFile(filePath, content) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, "utf8");
}

function removePath(targetPath) {
  fs.rmSync(targetPath, { recursive: true, force: true });
}

function walkFiles(dirPath) {
  const files = [];
  if (!fs.existsSync(dirPath)) return files;

  for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkFiles(fullPath));
    } else if (entry.isFile()) {
      files.push(fullPath);
    }
  }

  return files.sort();
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function extractFrontmatterVersion(filePath) {
  const match = mustRead(filePath).match(/^version:\s*(.+)$/m);
  return match ? match[1].trim() : null;
}

function lowerFirst(value) {
  if (!value) return value;
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function titleCaseSlug(slug) {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function buildCommandMappings() {
  return commands.map((command) => {
    const slug = command.command.replace(/^\//, "");
    const baseSkill = codex.commandBaseSkills?.[slug];
    if (!baseSkill) {
      throw new Error(`Missing codex.commandBaseSkills mapping for command slug: ${slug}`);
    }

    return {
      command,
      slug,
      baseSkill,
      wrapperName: `${codex.wrapperPrefix}-${slug}`
    };
  });
}

function buildCodexWorkspaceReadme() {
  return `# Codex APODICTIC Workspace

<!-- Generated by scripts/build-codex.mjs. Do not edit files in codex/ by hand. -->

This workspace is generated from the canonical APODICTIC source in this repo.

## Install In Codex

1. From the repo root, run:

\`\`\`bash
node scripts/build-codex.mjs
\`\`\`

2. Open this generated \`codex/\` folder as your Codex workspace root.
3. In Codex, open the Plugins view and install \`APODICTIC\` from the local marketplace in \`.agents/plugins/marketplace.json\`.
4. Start a fresh thread and run \`apodictic-start\`.

If APODICTIC does not appear in Codex, the most common cause is opening the wrong folder. The workspace root must be this generated \`codex/\` directory, not the repo root.

## Update The Plugin

1. Pull or edit the main repo.
2. Re-run \`node scripts/build-codex.mjs\`.
3. Reopen or refresh the generated \`codex/\` workspace in Codex.
4. Reinstall APODICTIC from the local marketplace if the installed copy is stale.

## Layout

- \`plugins/apodictic/\` — generated Codex plugin workspace
- \`.agents/plugins/marketplace.json\` — generated local marketplace entry
- \`NON_PARITY_NOTES.md\` — generated Codex parity notes

## Source Of Truth

- \`plugins/apodictic/\` — canonical authored APODICTIC source
- \`plugins/apodictic/*.codex.*\` — authored Codex-only overrides
- \`scripts/build-codex.mjs\` — generator for this workspace and package
`;
}

function buildWrapperDescription(wrapperName, command, slashCommand) {
  const clauses = [`the user explicitly asks for \`${wrapperName}\``];

  if (command.writerQuestion) {
    clauses.push(`they say something like "${command.writerQuestion}"`);
  }

  if (command.description) {
    clauses.push(`they want ${lowerFirst(command.description.replace(/\.$/, ""))}`);
  }

  return [
    "Codex-generated wrapper for APODICTIC's compatibility command surface.",
    `Use when ${clauses.join(", or when ")}.`,
    `This wrapper mirrors the legacy \`${slashCommand}\` behavior.`
  ].join(" ");
}

function buildWrapperSkill({ wrapperName, slashCommand, slug, baseSkill, command, version }) {
  const title = titleCaseSlug(slug);

  return `---
name: ${wrapperName}
description: >
  ${buildWrapperDescription(wrapperName, command, slashCommand)}
version: ${version}
---

<!-- Generated by scripts/build-codex.mjs. Do not edit files in codex/ by hand. -->

# APODICTIC ${title}

This generated skill exposes the legacy \`${slashCommand}\` workflow in Codex without duplicating the shared APODICTIC runtime.

## Load Order

1. Read \`../../commands/${slug}.md\` as the canonical command behavior.
2. Read \`../${baseSkill}/SKILL.md\`.
3. Load only the references, companion skills, and output rules that those source files call for.

## Execution Notes

- Preserve the command's routing, output, and resume behavior.
- Skip redundant intake when router output or project state has already prefilled the needed context.
- Keep artifact writing aligned with the shared APODICTIC specs, including the manuscript-adjacent output folder rules.
`;
}

function buildMarketplaceJson(manifest) {
  return {
    name: manifest.name,
    interface: {
      displayName: codex.displayName
    },
    plugins: [
      {
        name: manifest.name,
        source: {
          source: "local",
          path: `./plugins/${manifest.name}`
        },
        policy: {
          installation: codex.policy.installation,
          authentication: codex.policy.authentication
        },
        category: codex.category
      }
    ]
  };
}

function replaceSlashCommands(content, replacements) {
  let next = content;

  for (const [slashCommand, wrapperName] of replacements) {
    const pattern = new RegExp(
      `(^|[^A-Za-z0-9_-])${escapeRegExp(slashCommand)}(?=($|[^A-Za-z0-9_-]))`,
      "gm"
    );
    next = next.replace(pattern, (_, prefix) => `${prefix}${wrapperName}`);
  }

  return next;
}

function compareTrees(expectedDir, actualDir) {
  const expectedFiles = walkFiles(expectedDir);
  const actualFiles = walkFiles(actualDir);
  const expectedMap = new Map(expectedFiles.map((file) => [path.relative(expectedDir, file), file]));
  const actualMap = new Map(actualFiles.map((file) => [path.relative(actualDir, file), file]));
  const diffs = [];

  for (const relPath of [...expectedMap.keys()].sort()) {
    if (!actualMap.has(relPath)) {
      diffs.push(`Missing generated file: ${relPath}`);
      continue;
    }

    const expectedBuffer = fs.readFileSync(expectedMap.get(relPath));
    const actualBuffer = fs.readFileSync(actualMap.get(relPath));
    if (!expectedBuffer.equals(actualBuffer)) {
      diffs.push(`Generated file differs: ${relPath}`);
    }
  }

  for (const relPath of [...actualMap.keys()].sort()) {
    if (!expectedMap.has(relPath)) {
      diffs.push(`Unexpected generated file: ${relPath}`);
    }
  }

  return diffs;
}

function stripSourceOnlyFiles(tempPluginDir, wrapperMappings) {
  for (const filePath of walkFiles(tempPluginDir)) {
    const baseName = path.basename(filePath);
    if (baseName === ".DS_Store" || baseName.includes(".codex.")) {
      fs.rmSync(filePath, { force: true });
    }
  }

  for (const { wrapperName } of wrapperMappings) {
    removePath(path.join(tempPluginDir, "skills", wrapperName));
  }
}

function applyOverrides(tempWorkspace) {
  for (const [sourceRelPath, destRelPath] of Object.entries(codex.overrides || {})) {
    const sourcePath = abs(sourceRelPath);
    mustExist(sourcePath);

    const destPath = path.join(tempWorkspace, destRelPath);
    ensureDir(path.dirname(destPath));
    fs.copyFileSync(sourcePath, destPath);
  }
}

function rewriteGeneratedDocs(tempWorkspace, wrapperMappings) {
  const replacements = wrapperMappings
    .map(({ command, wrapperName }) => [command.command, wrapperName])
    .sort((left, right) => right[0].length - left[0].length);

  for (const filePath of walkFiles(tempWorkspace)) {
    if (!/\.(md|html)$/.test(filePath)) continue;
    const current = mustRead(filePath);
    const replaced = replaceSlashCommands(current, replacements);
    if (current !== replaced) {
      writeFile(filePath, replaced);
    }
  }
}

function stampGeneratedReadme(tempPluginDir, version) {
  const readmePath = path.join(tempPluginDir, "README.md");
  if (!fs.existsSync(readmePath)) return;

  let content = mustRead(readmePath);
  content = content.replace(
    /Current Codex manifest version is `[^`]+`/,
    `Current Codex manifest version is \`${version}\``
  );
  writeFile(readmePath, content);
}

function stampGeneratedManifest(tempPluginDir, canonicalManifest, version) {
  const manifestPath = path.join(tempPluginDir, ".codex-plugin", "plugin.json");
  const manifest = readJson(manifestPath);

  manifest.name = canonicalManifest.name;
  manifest.version = version;
  manifest.description = canonicalManifest.description;
  manifest.author = canonicalManifest.author;
  manifest.keywords = canonicalManifest.keywords;
  manifest.interface = manifest.interface || {};
  manifest.interface.displayName = codex.displayName;
  manifest.interface.category = codex.category;
  manifest.interface.defaultPrompt = codex.defaultPrompts;

  writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

function generateWrapperSkills(tempPluginDir, wrapperMappings, version) {
  for (const mapping of wrapperMappings) {
    const commandPath = path.join(tempPluginDir, "commands", `${mapping.slug}.md`);
    mustExist(commandPath);

    const baseSkillPath = path.join(tempPluginDir, "skills", mapping.baseSkill, "SKILL.md");
    mustExist(baseSkillPath);

    const wrapperDir = path.join(tempPluginDir, "skills", mapping.wrapperName);
    ensureDir(wrapperDir);
    writeFile(
      path.join(wrapperDir, "SKILL.md"),
        buildWrapperSkill({
          wrapperName: mapping.wrapperName,
          slashCommand: mapping.command.command,
          slug: mapping.slug,
          baseSkill: mapping.baseSkill,
          command: mapping.command,
          version
        })
      );
    }
  }

function writeWorkspaceRootFiles(tempWorkspace, tempPluginDir) {
  writeFile(path.join(tempWorkspace, "README.md"), buildCodexWorkspaceReadme());

  const manifest = readJson(path.join(tempPluginDir, ".codex-plugin", "plugin.json"));
  writeFile(
    path.join(tempWorkspace, ".agents", "plugins", "marketplace.json"),
    `${JSON.stringify(buildMarketplaceJson(manifest), null, 2)}\n`
  );
}

function validateManifestAssets(tempPluginDir, manifest) {
  const interfaceBlock = manifest.interface || {};
  const assetFields = [];

  if (typeof interfaceBlock.composerIcon === "string") {
    assetFields.push(interfaceBlock.composerIcon);
  }
  if (typeof interfaceBlock.logo === "string") {
    assetFields.push(interfaceBlock.logo);
  }
  if (Array.isArray(interfaceBlock.screenshots)) {
    assetFields.push(...interfaceBlock.screenshots);
  }

  for (const relAssetPath of assetFields) {
    const trimmed = relAssetPath.replace(/^\.\//, "");
    mustExist(path.join(tempPluginDir, trimmed));
  }
}

function validateGeneratedWorkspace(tempWorkspace, tempPluginDir, wrapperMappings, version, tempArchivePath) {
  const manifestPath = path.join(tempPluginDir, ".codex-plugin", "plugin.json");
  const manifest = readJson(manifestPath);
  const marketplacePath = path.join(tempWorkspace, ".agents", "plugins", "marketplace.json");
  readJson(marketplacePath);

  validateManifestAssets(tempPluginDir, manifest);

  for (const assetRelPath of codex.requiredAssets || []) {
    mustExist(path.join(tempWorkspace, assetRelPath));
  }

  for (const { wrapperName } of wrapperMappings) {
    mustExist(path.join(tempPluginDir, "skills", wrapperName, "SKILL.md"));
  }

  for (const skillPath of walkFiles(path.join(tempPluginDir, "skills")).filter((file) => path.basename(file) === "SKILL.md")) {
    const skillVersion = extractFrontmatterVersion(skillPath);
    if (skillVersion !== version) {
      throw new Error(
        `Skill version mismatch in ${path.relative(repoRoot, skillPath)}. Expected ${version}, found ${skillVersion || "missing"}.`
      );
    }
  }

  for (const commandPath of walkFiles(path.join(tempPluginDir, "commands")).filter((file) => file.endsWith(".md"))) {
    const content = mustRead(commandPath);
    if (/`references\/|`specialized-audits`|`plot-architecture`|`pre-writing-pathway`/.test(content)) {
      throw new Error(`Found ambiguous shorthand path in generated command doc: ${path.relative(repoRoot, commandPath)}`);
    }
  }

  for (const docPath of walkFiles(tempPluginDir).filter((file) => file.endsWith(".md"))) {
    if (/Outputs\/\[Project\]/.test(mustRead(docPath))) {
      throw new Error(`Found legacy Outputs/[Project] wording in generated doc: ${path.relative(repoRoot, docPath)}`);
    }
  }

  // Broad scan across generated markdown, with narrow allowlist exclusions for
  // intentional historical/provenance references that should survive generation.
  const runtimeDocs = walkFiles(tempWorkspace)
    .filter((file) => file.endsWith(".md"))
    .filter((file) => {
      const relPath = path.relative(tempWorkspace, file);
      return !new Set([
        "NON_PARITY_NOTES.md",
        "plugins/apodictic/skills/core-editor/references/changelog.md",
        "plugins/apodictic/skills/core-editor/references/output-policy.md",
        "plugins/apodictic/skills/specialized-audits/references/craft/adversarial-evidence-review.md"
      ]).has(relPath);
    });
  const badRuntimePatterns = [
    /Claude Opus/,
    /\.claude-plugin\/plugin\.json/,
    /After diagnosis, you work with Claude directly/,
    /Claude loads the full audit/,
    /Claude activates internet-enabled research/
  ];
  for (const docPath of runtimeDocs) {
    const content = mustRead(docPath);
    for (const pattern of badRuntimePatterns) {
      if (pattern.test(content)) {
        throw new Error(`Found Claude-specific runtime assumption in generated doc: ${path.relative(repoRoot, docPath)}`);
      }
    }
  }

  execFileSync(
    "zip",
    [
      "-X",
      "-rq",
      tempArchivePath,
      "README.md",
      "NON_PARITY_NOTES.md",
      ".agents",
      "plugins",
      "-x",
      "plugins/apodictic/.claude-plugin/*",
      "-x",
      "*/.DS_Store"
    ],
    { cwd: tempWorkspace }
  );

  const archiveEntries = execFileSync("unzip", ["-Z1", tempArchivePath], { encoding: "utf8" })
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  const requiredArchiveEntries = [
    "README.md",
    "NON_PARITY_NOTES.md",
    ".agents/plugins/marketplace.json",
    "plugins/apodictic/.codex-plugin/plugin.json",
    "plugins/apodictic/scripts/preflight.sh",
    "plugins/apodictic/scripts/validate.sh"
  ];
  for (const { wrapperName } of wrapperMappings) {
    requiredArchiveEntries.push(`plugins/apodictic/skills/${wrapperName}/SKILL.md`);
  }

  for (const entry of requiredArchiveEntries) {
    if (!archiveEntries.includes(entry)) {
      throw new Error(`Missing required archive entry: ${entry}`);
    }
  }

  if (archiveEntries.some((entry) => entry.startsWith("plugins/apodictic/.claude-plugin/"))) {
    throw new Error("Codex archive unexpectedly contains .claude-plugin content.");
  }
}

function main() {
  const canonicalManifestPath = abs(paths.pluginJson);
  const canonicalManifest = readJson(canonicalManifestPath);
  const canonicalVersion = canonicalManifest.version;
  const codexTemplatePath = abs("plugins/apodictic/.codex-plugin/plugin.json");
  const codexTemplate = readJson(codexTemplatePath);

  if (codexTemplate.version !== canonicalVersion) {
    throw new Error(
      `Codex manifest template version is ${codexTemplate.version}, expected ${canonicalVersion}. Run scripts/bump-version.sh ${canonicalVersion}.`
    );
  }

  const wrapperMappings = buildCommandMappings();
  const workspaceDir = abs(codex.workspaceDir);
  const archivePath = abs(codex.distArchive);
  const tempRoot = fs.mkdtempSync(path.join(repoRoot, ".codex-build-tmp-"));
  const tempWorkspace = path.join(tempRoot, "codex");
  const tempPluginDir = path.join(tempWorkspace, "plugins", "apodictic");
  const tempArchivePath = path.join(tempRoot, path.basename(archivePath));

  try {
    ensureDir(path.join(tempWorkspace, "plugins"));
    ensureDir(path.join(tempWorkspace, ".agents", "plugins"));

    fs.cpSync(abs("plugins/apodictic"), tempPluginDir, { recursive: true });

    stripSourceOnlyFiles(tempPluginDir, wrapperMappings);
    applyOverrides(tempWorkspace);
    rewriteGeneratedDocs(tempWorkspace, wrapperMappings);
    stampGeneratedReadme(tempPluginDir, canonicalVersion);
    stampGeneratedManifest(tempPluginDir, canonicalManifest, canonicalVersion);
    generateWrapperSkills(tempPluginDir, wrapperMappings, canonicalVersion);
    writeWorkspaceRootFiles(tempWorkspace, tempPluginDir);
    validateGeneratedWorkspace(
      tempWorkspace,
      tempPluginDir,
      wrapperMappings,
      canonicalVersion,
      tempArchivePath
    );

    if (checkOnly) {
      if (!fs.existsSync(workspaceDir)) {
        throw new Error("Generated codex workspace is missing. Run scripts/build-codex.mjs.");
      }

      const diffs = compareTrees(tempWorkspace, workspaceDir);
      if (diffs.length > 0) {
        const preview = diffs.slice(0, 40).map((diff) => `- ${diff}`).join("\n");
        const remainder = diffs.length > 40 ? `\n- ... (${diffs.length - 40} more)` : "";
        throw new Error(`Generated codex workspace is stale.\n${preview}${remainder}`);
      }

      console.log("build-codex check passed.");
      return;
    }

    ensureDir(path.dirname(archivePath));
    removePath(workspaceDir);
    fs.renameSync(tempWorkspace, workspaceDir);
    fs.copyFileSync(tempArchivePath, archivePath);

    console.log(`Generated workspace: ${path.relative(repoRoot, workspaceDir)}`);
    console.log(`Created archive: ${path.relative(repoRoot, archivePath)}`);
  } finally {
    removePath(tempRoot);
  }
}

try {
  main();
} catch (error) {
  console.error(`build-codex failed: ${error.message}`);
  process.exit(1);
}
